SET FOREIGN_KEY_CHECKS = 0;
truncate table Audit;
truncate table Merge;
truncate table MProvider_PracticeAddress;
truncate table MProvider_MailingAddress;
truncate table MProvider_PrimarySpecialty;
truncate table MProvider_SecondarySpecialty;
truncate table MProvider_PhoneNumber;
truncate table MIndividual;
truncate table MOrganization;
truncate table MProvider;
SET FOREIGN_KEY_CHECKS = 1;
