class Sequel::Dataset
   # Check if the data is present in the database. If it is, return the columns
   # specified in id. If it isn't, insert it and return the autogenerated key,
   # if any.
   #
   # The id parameter lets you specifiy the primary key, allowing consistent
   # return values whether or not the data is inserted.
   # @param id A symbol or array of symbols representing the columns which make
   # up the primary key.
   # @param data The data to be inserted.
   def check_insert id, data
      where(data).get(id) or
         insert data
   end
end
